# Generated by Django 6.0 on 2025-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=150)),
                ('roll_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
